//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rented
    {
        public int RentId { get; set; }
        public int aracId { get; set; }
        public int uyeId { get; set; }
        public string RentTarih { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
